<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>eu.maveniverse.maven.scalpel.it.skipteststestjar</groupId>
        <artifactId>skip-tests-test-jar</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>module-b</artifactId>

    <name>${project.groupId}:${project.artifactId}</name>

    <!-- The module changed by setup.groovy. Depends on module-common's main jar only. -->
    <dependencies>
        <dependency>
            <groupId>eu.maveniverse.maven.scalpel.it.skipteststestjar</groupId>
            <artifactId>module-common</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
